/**
 * HTML rendering for evidence packets (§8.1.2).
 *
 * Markdown remains canonical; HTML is the print source for wkhtmltopdf
 * in the self-hosted PDF/A container. Raw HTML in markdown source and
 * model-influenced text is escaped at parse time and sanitized again
 * before injection.
 */

import { Marked } from 'marked';

const PRINT_CSS = `
  @page {
    size: A4;
    margin: 2cm 2.2cm;
  }
  body {
    font-family: "Liberation Serif", "DejaVu Serif", Georgia, serif;
    font-size: 11pt;
    line-height: 1.45;
    color: #111;
  }
  h1 {
    font-size: 20pt;
    margin: 0 0 0.75rem;
    border-bottom: 2px solid #222;
    padding-bottom: 0.35rem;
  }
  h2 {
    font-size: 14pt;
    margin: 1.5rem 0 0.5rem;
    border-bottom: 1px solid #ccc;
    padding-bottom: 0.2rem;
  }
  h3 {
    font-size: 12pt;
    margin: 1rem 0 0.35rem;
  }
  p, li {
    margin: 0.35rem 0;
  }
  ul {
    padding-left: 1.25rem;
  }
  pre {
    font-family: "Liberation Mono", "DejaVu Sans Mono", monospace;
    font-size: 8.5pt;
    background: #f6f6f6;
    border: 1px solid #ddd;
    padding: 0.6rem;
    white-space: pre-wrap;
    word-break: break-word;
    page-break-inside: avoid;
  }
  code {
    font-family: "Liberation Mono", "DejaVu Sans Mono", monospace;
    font-size: 9pt;
  }
  hr {
    border: none;
    border-top: 1px solid #ddd;
    margin: 1.25rem 0;
  }
  .meta {
    font-size: 9pt;
    color: #444;
    margin-bottom: 1rem;
  }
`;

const DANGEROUS_TAG_NAMES = [
  'script',
  'iframe',
  'object',
  'embed',
  'form',
  'base',
  'meta',
] as const;

/** marked instance: raw HTML blocks in markdown are escaped, not passed through. */
const packetMarked = new Marked();
packetMarked.use({
  walkTokens(token) {
    if (token.type === 'html') {
      const escaped = escapeHtml(token.text);
      token.type = 'text';
      token.text = escaped;
      token.raw = escaped;
    }
  },
});

/**
 * Apply one regex replacement repeatedly until the string stabilizes.
 * CodeQL requires this pattern for multi-character sanitization (issue #65).
 */
function replaceUntilStable(input: string, pattern: RegExp, replacement = ''): string {
  let out = input;
  let previous: string;
  do {
    previous = out;
    out = out.replace(pattern, replacement);
  } while (out !== previous);
  return out;
}

/** Strip active content and external resource loads from marked HTML output. */
export function sanitizePacketHtml(html: string): string {
  let out = html;

  for (const tag of DANGEROUS_TAG_NAMES) {
    out = replaceUntilStable(
      out,
      new RegExp(`<\\s*${tag}\\b[^>]*>[\\s\\S]*?<\\s*\\/\\s*${tag}\\s*>`, 'gi')
    );
    out = replaceUntilStable(out, new RegExp(`<\\s*${tag}\\b[^>]*\\/?>`, 'gi'));
  }

  out = replaceUntilStable(out, /\s+on[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi);
  out = replaceUntilStable(
    out,
    /\s(href|src|xlink:href)\s*=\s*(["'])\s*javascript:[^"']*\2/gi
  );
  out = replaceUntilStable(
    out,
    /<\s*img\b[^>]*\ssrc\s*=\s*(["'])https?:[^"']*\1[^>]*>/gi
  );
  out = replaceUntilStable(
    out,
    /<\s*link\b[^>]*\shref\s*=\s*(["'])https?:[^"']*\1[^>]*>/gi
  );

  return out;
}

export function packetDocumentTitle(investigationId: string, runId: number): string {
  return `Common Thread Evidence Packet — ${investigationId} — run ${runId}`;
}

export async function packetMarkdownToHtml(
  markdown: string,
  title: string
): Promise<string> {
  const parsed = await packetMarked.parse(markdown);
  const body = sanitizePacketHtml(parsed);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>${PRINT_CSS}</style>
</head>
<body>
  <div class="meta">Generated by Common Thread reference implementation (evidence-packet-v1)</div>
  ${body}
</body>
</html>`;
}

function escapeHtml(value: string): string {
  let out = value;
  out = replaceUntilStable(out, /&/g, '&amp;');
  out = replaceUntilStable(out, /</g, '&lt;');
  out = replaceUntilStable(out, />/g, '&gt;');
  out = replaceUntilStable(out, /"/g, '&quot;');
  return out;
}
