/**
 * HTML rendering for evidence packets (§8.1.2).
 *
 * Markdown remains canonical; HTML is the print source for wkhtmltopdf
 * in the self-hosted PDF/A container.
 */

import { marked } from 'marked';

const PRINT_CSS = `
  @page {
    size: A4;
    margin: 2cm 2.2cm;
  }
  body {
    font-family: "Liberation Serif", "DejaVu Serif", Georgia, serif;
    font-size: 11pt;
    line-height: 1.45;
    color: #111;
  }
  h1 {
    font-size: 20pt;
    margin: 0 0 0.75rem;
    border-bottom: 2px solid #222;
    padding-bottom: 0.35rem;
  }
  h2 {
    font-size: 14pt;
    margin: 1.5rem 0 0.5rem;
    border-bottom: 1px solid #ccc;
    padding-bottom: 0.2rem;
  }
  h3 {
    font-size: 12pt;
    margin: 1rem 0 0.35rem;
  }
  p, li {
    margin: 0.35rem 0;
  }
  ul {
    padding-left: 1.25rem;
  }
  pre {
    font-family: "Liberation Mono", "DejaVu Sans Mono", monospace;
    font-size: 8.5pt;
    background: #f6f6f6;
    border: 1px solid #ddd;
    padding: 0.6rem;
    white-space: pre-wrap;
    word-break: break-word;
    page-break-inside: avoid;
  }
  code {
    font-family: "Liberation Mono", "DejaVu Sans Mono", monospace;
    font-size: 9pt;
  }
  hr {
    border: none;
    border-top: 1px solid #ddd;
    margin: 1.25rem 0;
  }
  .meta {
    font-size: 9pt;
    color: #444;
    margin-bottom: 1rem;
  }
`;

export function packetDocumentTitle(investigationId: string, runId: number): string {
  return `Common Thread Evidence Packet — ${investigationId} — run ${runId}`;
}

export async function packetMarkdownToHtml(
  markdown: string,
  title: string
): Promise<string> {
  const body = await marked.parse(markdown);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>${PRINT_CSS}</style>
</head>
<body>
  <div class="meta">Generated by Common Thread reference implementation (evidence-packet-v1)</div>
  ${body}
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
